export const AUDIT_ACTIONS = {
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_STATUS_CHANGED: 'BOOKING_STATUS_CHANGED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_PRICE_UPDATED: 'BOOKING_PRICE_UPDATED',
  ROOM_STATUS_CHANGED: 'ROOM_STATUS_CHANGED',
} as const;

export const AUDIT_TARGET_TABLES = {
  BOOKINGS: 'bookings',
  ROOMS: 'rooms',
} as const;
